export const ACCOUNT_LIST_REQUEST = 'ACCOUNT_LIST_REQUEST';
export const ACCOUNT_LIST_SUCCESS = 'ACCOUNT_LIST_SUCCESS';
export const ACCOUNT_LIST_FAIL = 'ACCOUNT_LIST_FAIL';

export const ACCOUNT_DELETE_REQUEST = 'ACCOUNT_DELETE_REQUEST';
export const ACCOUNT_DELETE_SUCCESS = 'ACCOUNT_DELETE_SUCCESS';
export const ACCOUNT_DELETE_FAIL = 'ACCOUNT_DELETE_FAIL';

export const ACCOUNT_ADD_REQUEST = 'ACCOUNT_ADD_REQUEST';
export const ACCOUNT_ADD_SUCCESS = 'ACCOUNT_ADD_SUCCESS';
export const ACCOUNT_ADD_FAIL = 'ACCOUNT_ADD_FAIL';
export const ACCOUNT_ADD_RESET = 'ACCOUNT_ADD_RESET';