# Generated by Django 3.1.5 on 2021-03-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget_app", "0006_account_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
