# Generated by Django 3.1.5 on 2021-03-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0007_account_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='balance',
            new_name='init_balance',
        ),
    ]
